Add Checkov checks

diff --git a/.github/workflows/scan.yml b/.github/workflows/scan.yml
--- a/.github/workflows/scan.yml
+++ b/.github/workflows/scan.yml
@@ -79,23 +79,60 @@ jobs:
         uses: actions/checkout@v3
         with:
           sparse-checkout: python/
-      # Bandit doesn't include the SARIF formatter by default.
-      # Also, it's not possible to generate screen output and SARIF results at the same time.
-#      - name: run bandit
-#        uses: PyCQA/bandit-action@v1.0.0
-#        with:
-#          args: |
-#            -r -f screen,xml,yaml,json,sarif
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.11'
+      # We're not using the official action because Bandit doesn't include the SARIF formatter by default.
       - name: install bandit
+        # we could bind a specific Bandit and SARIF formatter version here
         run: |
           pip install bandit bandit_sarif_formatter
+      # Need to run Bandit twice because of https://github.com/PyCQA/bandit/issues/1047
       - name: generate sarif report
-        # ignore errors here (--exit-zero) so we can keep going
+        # ignore errors here (--exit-zero) so we can keep going (and fail with a full report)
         run: |
           bandit --recursive --format sarif --output results.sarif --exit-zero python/
       - name: run bandit
         run: |
           bandit --recursive --format screen python/
+      - name: upload results
+        uses: github/codeql-action/upload-sarif@v2
+        if: success() || failure()
+        continue-on-error: true
+        with:
+          sarif_file: results.sarif
+  chekov-terraform:
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout repo
+        uses: actions/checkout@v3
+        with:
+          sparse-checkout: terraform/
+      - name: run chekov
+        uses: bridgecrewio/checkov-action@v12
+        with:
+          directory: terraform/
+          output_format: cli,sarif
+          output_file_path: console,results.sarif
+      - name: upload results
+        uses: github/codeql-action/upload-sarif@v2
+        if: success() || failure()
+        continue-on-error: true
+        with:
+          sarif_file: results.sarif
+  chekov-bicep:
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout repo
+        uses: actions/checkout@v3
+        with:
+          sparse-checkout: bicep/
+      - name: run chekov
+        uses: bridgecrewio/checkov-action@v12
+        with:
+          directory: bicep/
+          output_format: cli,sarif
+          output_file_path: console,results.sarif
       - name: upload results
         uses: github/codeql-action/upload-sarif@v2
         if: success() || failure()
